development:
  host: localhost
  port: 27017
  database: anchor_development

test:
  host: localhost
  port: 27017
  database: anchor_test

staging:
  hosts: [[staging2.copious.com, 27017], [staging.copious.com, 27017], [staging3.copious.com, 27017]]
  database: anchor_staging
  read_secondary: true
  max_retries_on_connection_failure: 3

demo:
  host: demo1.copious.com
  port: 27017
  database: anchor_demo

production:
  hosts: [[anchor-mongo-1.copious.com, 27017], [anchor-mongo-2.copious.com, 27017], [anchor-mongo-3.copious.com, 27017]]
  database: anchor_production
  read_secondary: true
  max_retries_on_connection_failure: 3
  logger: false
